version: '2'
services:
    nginx:
        # используем последний стабильный образ nginx
        image: nginx:latest
        # маршрутизируем порты
        ports:
            - "80:80"
            - "443:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        # nginx должен общаться с php контейнером
        links:
            - php
    php:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php
        # этот образ будет общаться с mysql
        links:
            - mysql
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www
    mysql:
       image: mariadb:10.3
       # volumes:
       #     - ./mysql:/var/lib/mysql
       ports:
           - "3306:3306"
       # задаем пароль для root пользователя
       environment:
            MYSQL_ROOT_PASSWORD: "secret"
    pma:
        # используем последний стабильный образ phpmyadmin
        image: phpmyadmin/phpmyadmin
        links:
            - mysql
        restart: always
        ports:
            - "8080:80"
        environment:
            # прописываем название нашего MySQL хоста
            PMA_HOST: "mysql"
            MYSQL_USERNAME: "root"
            MYSQL_ROOT_PASSWORD: "secret"