version: '2'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        links:
            - php
    php:
        build: ./images/php
        links:
            - mysql
        volumes:
            - ./www:/var/www
    mysql:
       image: mariadb:10.3
       # volumes:
       #     - ./mysql:/var/lib/mysql
       ports:
           - "3306:3306"
       environment:
            MYSQL_ROOT_PASSWORD: "secret"
    pma:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql
        restart: always
        ports:
            - "8080:80"
        environment:
            PMA_HOST: "mysql"
            MYSQL_USERNAME: "root"
            MYSQL_ROOT_PASSWORD: "secret"